id: A549759F8
title: Maṇḍala Offering from Longsal Dorje Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:34:23.661114
  last_modified_at: 2022-03-01 04:34:23.661117
