id: A549759F8
title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:34:23.662824
  last_modified_at: 2022-03-01 04:34:23.662829
