id: A549759F8
title: Short Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:34:23.663862
  last_modified_at: 2022-03-01 04:34:23.663865
